#!/usr/bin/env python3
r"""Command line interface for running and displaying results of transfer attacks."""

from transferbench.benchmark_tools.main_bnch_tool import main

if __name__ == "__main__":
    main()
