
"gfcs":
  - hp:
      maximum_queries: 100
      p: 2
      eps: 12.26898 # (0.001*224*224*3)**0.5
    victim_model: "vgg16"
    surrogate_models: ["vgg19", "resnet34", "densenet121", "mobilenet_v2"]
    dataset: "ImageNetT"
