"nes":
  - hp:
      maximum_queries: 1000
      p: "inf"
      eps: 0.062745 # 16/255
    victim_model: "vgg13"
    surrogate_models: ["vgg13", "vgg19"]
    dataset: "ImageNetT"

"nes_fast":
  - hp:
      maximum_queries: 200
      p: "inf"
      eps: 0.062745 # 16/255
    victim_model: "vgg13"
    surrogate_models: ["vgg13", "vgg19"]
    dataset: "ImageNetT"

"nes_slow":
  - hp:
      maximum_queries: 2000
      p: "inf"
      eps: 0.062745 # 16/255
    victim_model: "vgg13"
    surrogate_models: ["vgg13", "vgg19"]
    dataset: "ImageNetT"

"nes_debug":
  - hp:
      maximum_queries: 4000
      p: "inf"
      eps: 0.062745 # 16/255
    victim_model: "vgg13"
    surrogate_models: ["vgg13", "vgg19"]
    dataset: "ImageNetT"